import { useEffect, useMemo, useState } from 'react'
import {
  Camera, Check, ChevronRight, Clock3, Crown, Flame, Home, Image, ListChecks,
  LoaderCircle, LockKeyhole, LogOut, Plus, ShieldCheck, Sparkles, Trophy,
  Upload, X, Trash2, WandSparkles, Eye, Users, CalendarClock, Swords
} from 'lucide-react'
import { supabase } from './supabase'

const NAV_ITEMS = [['home','Home',Home],['challenges','Opdrachten',ListChecks],['feed','Feed',Image],['leaderboard','Stand',Trophy]]
const CATEGORY_EMOJI = { Mallorca:'🌴', Feest:'🍻', Sociaal:'🤝', Strafpunten:'🫠', Muziek:'🎤', Bonus:'⚡', 'Moment van de dag':'☀️', Geheim:'🕵️', Kaapbaar:'🏴‍☠️', Overig:'🎯' }
const participantNames = ['Rens','Jorg','Sven','Gijs','Thomas','Jens','Sil']

function formatDate(value){ return new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)) }
function toLocalInput(value){ if(!value) return ''; const d=new Date(value); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16) }
function timeLeft(end){ const ms=Math.max(0,new Date(end)-Date.now()); return `${Math.floor(ms/86400000)}d ${Math.floor((ms%86400000)/3600000)}u ${Math.floor((ms%3600000)/60000)}m` }
function isAvailable(c){ const now=Date.now(); return (!c.available_from || new Date(c.available_from).getTime()<=now) && (!c.available_until || new Date(c.available_until).getTime()>=now) }

function Login({onLogin}){
  const [name,setName]=useState('Rens'),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const names=[...participantNames,'Jury','Admin','Publiek']
  async function submit(e){ e.preventDefault(); setBusy(true); setError(''); const email=`${name.toLowerCase()}@mallorca-madness.local`; const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error)setError('Inloggen mislukt. Controleer naam en wachtwoord.'); else onLogin(data.session); setBusy(false) }
  return <main className="login-page"><div className="sun-orb"/><section className="login-card glass"><div className="brand-mark">MM</div><p className="eyebrow">23–30 juli 2026</p><h1>Mallorca<br/><em>Madness</em></h1><p className="muted">Zon, opdrachten, bier, cocktails en eeuwige roem.</p><form onSubmit={submit} className="login-form"><label>Wie ben je?</label><select value={name} onChange={e=>setName(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select><label>Wachtwoord</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<LockKeyhole/>} Inloggen</button></form></section></main>
}

export default function App(){
  const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[page,setPage]=useState('home'),[loading,setLoading]=useState(true),[showSubmit,setShowSubmit]=useState(false)
  const [data,setData]=useState({settings:null,profiles:[],challenges:[],submissions:[],participants:[],leaderboard:[]})
  useEffect(()=>{ supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>l.subscription.unsubscribe() },[])
  useEffect(()=>{if(session)loadAll()},[session])
  useEffect(()=>{if(!session)return; const ch=supabase.channel('mm-live-v3').on('postgres_changes',{event:'*',schema:'public',table:'submissions'},loadAll).on('postgres_changes',{event:'*',schema:'public',table:'submission_participants'},loadAll).on('postgres_changes',{event:'*',schema:'public',table:'challenges'},loadAll).subscribe(); return()=>supabase.removeChannel(ch)},[session])
  async function loadAll(){
    const [settings,profiles,challenges,submissions,sp,leaderboard]=await Promise.all([
      supabase.from('game_settings').select('*').single(), supabase.from('profiles').select('*').order('display_name'),
      supabase.from('challenges').select('*').eq('active',true).order('created_at'),
      supabase.from('submissions').select('*, challenges(*), profiles!submissions_submitted_by_fkey(display_name)').order('submitted_at',{ascending:false}),
      supabase.from('submission_participants').select('*'), supabase.from('leaderboard').select('*').order('points',{ascending:false})])
    const mine=profiles.data?.find(p=>p.id===session.user.id); setProfile(mine); setData({settings:settings.data,profiles:profiles.data||[],challenges:challenges.data||[],submissions:submissions.data||[],participants:sp.data||[],leaderboard:leaderboard.data||[]})
  }
  async function logout(){await supabase.auth.signOut();setSession(null);setProfile(null)}
  if(loading)return <div className="splash"><LoaderCircle className="spin"/></div>; if(!session)return <Login onLogin={setSession}/>; if(!profile)return <div className="splash"><LoaderCircle className="spin"/><p>Profiel laden…</p></div>
  const isStaff=['jury','admin'].includes(profile.role), isViewer=profile.role==='spectator', approved=data.submissions.filter(s=>s.status==='approved'), pending=data.submissions.filter(s=>['pending','needs_evidence'].includes(s.status))
  return <div className="app-shell"><header className="topbar"><div className="mini-brand"><span>MM</span><div><strong>Mallorca Madness</strong><small>{isViewer?'Toeschouwersmodus':'Live score'}</small></div></div><div className="top-actions"><span className="user-chip">{profile.display_name}</span><button className="icon-button" onClick={logout}><LogOut size={19}/></button></div></header>
    <main className="content">{page==='home'&&<HomePage data={data} approved={approved} pending={pending} profile={profile} onNavigate={setPage} onSubmit={()=>setShowSubmit(true)}/>} {page==='challenges'&&<ChallengesPage data={data} profile={profile} onSubmit={()=>setShowSubmit(true)}/>} {page==='feed'&&<FeedPage submissions={approved} participants={data.participants} profiles={data.profiles}/>} {page==='leaderboard'&&<LeaderboardPage leaderboard={data.leaderboard}/>} {page==='jury'&&isStaff&&<JuryPage submissions={pending} data={data} profile={profile} refresh={loadAll}/>} {page==='admin'&&profile.role==='admin'&&<AdminPage data={data} refresh={loadAll}/>}</main>
    <nav className="bottom-nav">{NAV_ITEMS.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/><span>{label}</span></button>)}{isStaff&&<button className={page==='jury'?'active':''} onClick={()=>setPage('jury')}><ShieldCheck/><span>Jury</span>{pending.length>0&&<b>{pending.length}</b>}</button>}{profile.role==='admin'&&<button className={page==='admin'?'active':''} onClick={()=>setPage('admin')}><WandSparkles/><span>Beheer</span></button>}</nav>
    {!isViewer&&<button className="fab" onClick={()=>setShowSubmit(true)}><Plus/><span>Indienen</span></button>}{showSubmit&&!isViewer&&<SubmitModal data={data} profile={profile} onClose={()=>setShowSubmit(false)} onDone={()=>{setShowSubmit(false);loadAll()}}/>}</div>
}

function HomePage({data,approved,pending,profile,onNavigate,onSubmit}){
  const moment=data.challenges.find(c=>c.challenge_type==='moment'&&isAvailable(c)), bonus=data.challenges.find(c=>c.challenge_type==='bonus'&&isAvailable(c)), top=data.leaderboard[0], viewer=profile.role==='spectator'
  return <><section className="hero-card"><div className="hero-copy"><p className="eyebrow">Welkom, {profile.display_name}</p><h2>Wie pakt de <em>eeuwige roem?</em></h2><div className="hero-meta"><span><Clock3/> {data.settings?timeLeft(data.settings.ends_at):'—'}</span><span><Flame/> {approved.length} voltooid</span></div></div><div className="palm-visual"><span>🍹</span><b>🌴</b></div></section>
  <section className="stat-grid"><article className="stat-card"><div className="stat-icon gold"><Crown/></div><small>Koploper</small><strong>{top?.display_name||'Nog niemand'}</strong><p>{top?.points||0} punten</p></article><article className="stat-card"><div className="stat-icon coral">🍺</div><small>In beoordeling</small><strong>{pending.length}</strong><p>inzendingen</p></article></section>
  {(moment||bonus)&&<section><div className="section-head"><div><p className="eyebrow">Nu live</p><h3>Specials</h3></div><Sparkles/></div><div className="special-grid">{moment&&<ChallengeCard challenge={moment} featured onSubmit={viewer?null:onSubmit}/>} {bonus&&<ChallengeCard challenge={bonus} onSubmit={viewer?null:onSubmit}/>}</div></section>}
  <section><div className="section-head"><div><p className="eyebrow">Live</p><h3>Top 3</h3></div><button className="text-button" onClick={()=>onNavigate('leaderboard')}>Volledige stand <ChevronRight/></button></div><div className="podium-list">{data.leaderboard.slice(0,3).map((p,i)=><div className="podium-row" key={p.id}><span className={`rank rank-${i+1}`}>{i+1}</span><div className="avatar">{p.display_name[0]}</div><div className="grow"><strong>{p.display_name}</strong><small>{p.completed} opdrachten</small></div><b>{p.points} pt</b></div>)}</div></section>
  <section><div className="section-head"><div><p className="eyebrow">Net gebeurd</p><h3>Laatste updates</h3></div><button className="text-button" onClick={()=>onNavigate('feed')}>Bekijk feed <ChevronRight/></button></div><div className="mini-feed">{approved.slice(0,3).map(s=><FeedCard key={s.id} submission={s} participants={data.participants} profiles={data.profiles}/>)}</div></section></>
}

function ChallengeCard({challenge,featured=false,onSubmit,completed=false}){
  return <article className={`challenge-card ${featured?'featured':''}`}><div className="challenge-top"><span className="category-pill">{CATEGORY_EMOJI[challenge.category]||'🎯'} {challenge.category}</span><span className={`points ${challenge.points<0?'negative':''}`}>{challenge.points>0?'+':''}{challenge.points}</span></div><h4>{challenge.title}</h4><p>{challenge.description}</p>{challenge.available_from&&<small className="availability"><CalendarClock/> Vanaf {formatDate(challenge.available_from)}</small>}{challenge.challenge_type==='claim'&&<small className="availability"><Swords/> Kaapbaar: beste prestatie houdt de punten</small>}{completed?<span className="completed-label"><Check/> Goedgekeurd</span>:onSubmit&&<button onClick={onSubmit}>Bewijs indienen <Upload/></button>}</article>
}

function ChallengesPage({data,profile,onSubmit}){
  const [filter,setFilter]=useState('Alle'), viewer=profile.role==='spectator'; const challenges=data.challenges.filter(c=>isAvailable(c)||['jury','admin'].includes(profile.role)); const categories=['Alle',...new Set(challenges.map(c=>c.category))], shown=filter==='Alle'?challenges:challenges.filter(c=>c.category===filter)
  const completedIds=new Set(data.participants.filter(sp=>sp.participant_id===profile.id).map(sp=>data.submissions.find(s=>s.id===sp.submission_id&&s.status==='approved')).filter(Boolean).map(s=>s.challenge_id))
  return <><PageIntro eyebrow="Missielijst" title="Alle opdrachten" text={viewer?'Bekijk wat er te verdienen valt en wat al is uitgevoerd.':'Normale opdrachten tellen één keer per persoon. Specials hebben hun eigen regels.'}/><div className="filter-row">{categories.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="challenge-list">{shown.map(c=><div className="challenge-wrap" key={c.id}><ChallengeCard challenge={c} completed={!viewer&&completedIds.has(c.id)&&c.challenge_type!=='moment'&&c.challenge_type!=='claim'} onSubmit={viewer?null:onSubmit}/></div>)}</div></>
}

function FeedPage({submissions,participants,profiles}){ return <><PageIntro eyebrow="Vakantiedagboek" title="Madness feed" text="Alle goedgekeurde opdrachten, inclusief wie er samen punten kregen."/><div className="feed-grid">{submissions.length?submissions.map(s=><FeedCard key={s.id} submission={s} participants={participants} profiles={profiles} large/>):<Empty text="Nog geen goedgekeurde inzendingen."/>}</div></> }
function FeedCard({submission,participants=[],profiles=[],large=false}){ const url=submission.photo_path?supabase.storage.from('proofs').getPublicUrl(submission.photo_path).data.publicUrl:null; const names=participants.filter(x=>x.submission_id===submission.id).map(x=>profiles.find(p=>p.id===x.participant_id)?.display_name).filter(Boolean)
  return <article className={`feed-card ${large?'large':''}`}>{url&&<img src={url} alt="Bewijs" loading="lazy"/>}<div className="feed-body"><div className="feed-user"><div className="avatar small">{submission.profiles?.display_name?.[0]||'?'}</div><div><strong>{names.length?names.join(', '):submission.profiles?.display_name}</strong><small>{formatDate(submission.submitted_at)}</small></div><span className={`points ${submission.challenges?.points<0?'negative':''}`}>{submission.challenges?.points>0?'+':''}{submission.challenges?.points}</span></div><h4>{submission.challenges?.title||'Geheime opdracht'}</h4>{submission.performance_value!=null&&<p className="performance">Prestatie: <strong>{submission.performance_value} {submission.challenges?.metric_unit||''}</strong></p>}{submission.note&&<p>{submission.note}</p>}</div></article> }
function LeaderboardPage({leaderboard}){ return <><PageIntro eyebrow="De waarheid" title="Leaderboard" text="Iedere geselecteerde deelnemer krijgt na goedkeuring de volledige punten van de opdracht."/><div className="leaderboard-card">{leaderboard.map((p,i)=><div className="leader-row" key={p.id}><span className={`rank rank-${i+1}`}>{i+1}</span><div className="avatar">{p.display_name[0]}</div><div className="grow"><strong>{p.display_name}</strong><small>{p.completed} goedgekeurd</small></div><div className="score"><b>{p.points}</b><small>punten</small></div></div>)}</div><section className="winner-banner"><Trophy/><div><small>Huidige winnaar</small><strong>{leaderboard[0]?.display_name||'Nog niemand'}</strong></div><Sparkles/></section></> }

function JuryPage({submissions,data,profile,refresh}){
  const [moment,setMoment]=useState({title:'',description:'',points:5,available_from:'',available_until:''}),[busy,setBusy]=useState(false)
  async function review(s,status){ const reason=status==='rejected'?prompt('Reden voor afwijzing:')||'Niet goedgekeurd':null; const {error}=await supabase.from('submissions').update({status,rejection_reason:reason,reviewed_at:new Date().toISOString(),reviewed_by:profile.id}).eq('id',s.id); if(error)alert(error.message); refresh() }
  async function publishMoment(e){e.preventDefault();setBusy(true);const payload={...moment,points:Number(moment.points),category:'Moment van de dag',challenge_type:'moment',repeat_type:'first_only',active:true,created_by:profile.id,available_from:new Date(moment.available_from).toISOString(),available_until:new Date(moment.available_until).toISOString()};const {error}=await supabase.from('challenges').insert(payload);if(error)alert(error.message);else setMoment({title:'',description:'',points:5,available_from:'',available_until:''});setBusy(false);refresh()}
  return <><PageIntro eyebrow="Controlekamer" title="Jury" text="Beoordeel inzendingen en zet zelf het moment van de dag live."/><section className="admin-grid"><form className="admin-card" onSubmit={publishMoment}><div className="section-head"><div><p className="eyebrow">Dag-special</p><h3>Moment van de dag plaatsen</h3></div><Clock3/></div><label>Titel</label><input required value={moment.title} onChange={e=>setMoment({...moment,title:e.target.value})}/><label>Omschrijving</label><textarea required value={moment.description} onChange={e=>setMoment({...moment,description:e.target.value})}/><div className="form-pair"><div><label>Punten</label><input type="number" value={moment.points} onChange={e=>setMoment({...moment,points:e.target.value})}/></div><div/></div><div className="form-pair"><div><label>Online vanaf</label><input required type="datetime-local" value={moment.available_from} onChange={e=>setMoment({...moment,available_from:e.target.value})}/></div><div><label>Sluit op dezelfde dag</label><input required type="datetime-local" value={moment.available_until} onChange={e=>setMoment({...moment,available_until:e.target.value})}/></div></div><button className="primary-button" disabled={busy}><Plus/> Online plaatsen</button></form></section>
  <div className="review-list">{submissions.length?submissions.map(s=><article className="review-card" key={s.id}><FeedCard submission={s} participants={data.participants} profiles={data.profiles} large/><div className="review-actions"><button className="approve" onClick={()=>review(s,'approved')}><Check/> Goedkeuren</button><button className="reject" onClick={()=>review(s,'rejected')}><X/> Afwijzen</button></div></article>):<Empty text="Alles is beoordeeld."/>}</div></>
}

function AdminPage({data,refresh}){
  const empty={title:'',description:'',points:5,category:'Feest',challenge_type:'normal',repeat_type:'once_person',assigned_to:'',available_from:'',available_until:'',metric_unit:'',better_is:'max'}
  const [form,setForm]=useState(empty),[busy,setBusy]=useState(false); const approved=data.submissions.filter(s=>s.status==='approved'), participants=data.profiles.filter(p=>p.role==='participant')
  function typeChanged(value){ const patch={challenge_type:value}; if(value==='moment')patch.repeat_type='first_only'; if(value==='bonus')patch.repeat_type='once_group'; if(value==='claim')patch.repeat_type='first_only'; setForm({...form,...patch}) }
  async function addChallenge(e){e.preventDefault();setBusy(true);const payload={...form,points:Number(form.points),active:true,assigned_to:form.challenge_type==='secret'?form.assigned_to||null:null,available_from:form.available_from?new Date(form.available_from).toISOString():null,available_until:form.available_until?new Date(form.available_until).toISOString():null,metric_unit:form.challenge_type==='claim'?form.metric_unit:null,better_is:form.challenge_type==='claim'?form.better_is:null};const {error}=await supabase.from('challenges').insert(payload);if(error)alert(error.message);else setForm(empty);setBusy(false);refresh()}
  async function removeSubmission(s){if(!confirm(`Verwijder “${s.challenges?.title}”? De punten verdwijnen direct.`))return;if(s.photo_path)await supabase.storage.from('proofs').remove([s.photo_path]);const {error}=await supabase.from('submissions').delete().eq('id',s.id);if(error)alert(error.message);refresh()}
  return <><PageIntro eyebrow="Beheer" title="Mallorca HQ" text="Maak normale, geheime, groeps-, kaapbare en later vrijkomende opdrachten."/><section className="admin-grid"><form className="admin-card" onSubmit={addChallenge}><div className="section-head"><div><p className="eyebrow">Nieuwe missie</p><h3>Opdracht toevoegen</h3></div><Plus/></div><label>Titel</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><label>Omschrijving</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="form-pair"><div><label>Punten</label><input type="number" value={form.points} onChange={e=>setForm({...form,points:e.target.value})}/></div><div><label>Categorie</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Feest</option><option>Mallorca</option><option>Sociaal</option><option>Muziek</option><option>Strafpunten</option><option>Bonus</option><option>Moment van de dag</option><option>Geheim</option><option>Kaapbaar</option><option>Overig</option></select></div></div><div className="form-pair"><div><label>Type</label><select value={form.challenge_type} onChange={e=>typeChanged(e.target.value)}><option value="normal">Normaal</option><option value="bonus">Bonus voor hele groep</option><option value="moment">Moment van de dag</option><option value="secret">Geheim per deelnemer</option><option value="claim">Kaapbare recordopdracht</option></select></div><div><label>Herhaling</label><select value={form.repeat_type} onChange={e=>setForm({...form,repeat_type:e.target.value})} disabled={['bonus','moment','claim'].includes(form.challenge_type)}><option value="once_person">1× per persoon</option><option value="first_only">Alleen één winnaar</option><option value="once_group">1× hele groep</option><option value="unlimited">Onbeperkt</option></select></div></div>
  {form.challenge_type==='secret'&&<><label>Alleen zichtbaar voor</label><select required value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value="">Kies deelnemer</option>{participants.map(p=><option value={p.id} key={p.id}>{p.display_name}</option>)}</select></>}
  {form.challenge_type==='claim'&&<div className="form-pair"><div><label>Eenheid</label><input required placeholder="shirts, seconden, glazen…" value={form.metric_unit} onChange={e=>setForm({...form,metric_unit:e.target.value})}/></div><div><label>Wat is beter?</label><select value={form.better_is} onChange={e=>setForm({...form,better_is:e.target.value})}><option value="max">Hoger</option><option value="min">Lager / sneller</option></select></div></div>}
  <div className="form-pair"><div><label>Beschikbaar vanaf (optioneel)</label><input type="datetime-local" value={form.available_from} onChange={e=>setForm({...form,available_from:e.target.value})}/></div><div><label>Beschikbaar tot (optioneel)</label><input type="datetime-local" value={form.available_until} onChange={e=>setForm({...form,available_until:e.target.value})}/></div></div><button className="primary-button" disabled={busy}><Plus/> Opdracht opslaan</button></form></section>
  <section><div className="section-head"><div><p className="eyebrow">Correcties</p><h3>Goedgekeurde inzendingen</h3></div><Trash2/></div><div className="admin-submissions">{approved.map(s=><div className="admin-submission" key={s.id}><div><strong>{s.profiles?.display_name}</strong><span>{s.challenges?.title} · {s.challenges?.points>0?'+':''}{s.challenges?.points} pt</span></div><button onClick={()=>removeSubmission(s)}><Trash2/> Verwijder</button></div>)}</div></section></>
}

function SubmitModal({data,profile,onClose,onDone}){
  const available=data.challenges.filter(isAvailable), [challengeId,setChallengeId]=useState(available[0]?.id||''),[note,setNote]=useState(''),[file,setFile]=useState(null),[selected,setSelected]=useState([profile.id]),[performance,setPerformance]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''); const participants=data.profiles.filter(p=>p.role==='participant'), challenge=available.find(c=>c.id===challengeId)
  useEffect(()=>{if(challenge?.challenge_type==='bonus')setSelected(participants.map(p=>p.id)); else if(challenge?.challenge_type==='secret')setSelected([profile.id]); else setSelected(v=>v.length?v:[profile.id])},[challengeId])
  function toggle(id){if(challenge?.challenge_type==='bonus'||challenge?.challenge_type==='secret')return;setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(!selected.length)throw new Error('Selecteer minimaal één deelnemer.'); if(challenge?.challenge_type==='secret'&&challenge.assigned_to!==profile.id)throw new Error('Deze geheime opdracht is niet voor jou.'); let photoPath=null;if(file){const ext=file.name.split('.').pop();photoPath=`${profile.id}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from('proofs').upload(photoPath,file);if(up.error)throw up.error}const {data:s,error}=await supabase.from('submissions').insert({challenge_id:challengeId,submitted_by:profile.id,note,photo_path:photoPath,status:'pending',performance_value:challenge?.challenge_type==='claim'?Number(performance):null}).select().single();if(error)throw error;const rows=selected.map(id=>({submission_id:s.id,participant_id:id}));const added=await supabase.from('submission_participants').insert(rows);if(added.error)throw added.error;onDone()}catch(err){setError(err.message||'Er ging iets mis.')}setBusy(false)}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal-card"><button className="modal-close" onClick={onClose}><X/></button><p className="eyebrow">Nieuw bewijs</p><h3>Opdracht indienen</h3><form onSubmit={submit} className="submit-form"><label>Opdracht</label><select value={challengeId} onChange={e=>setChallengeId(e.target.value)}>{available.map(c=><option value={c.id} key={c.id}>{c.title} ({c.points>0?'+':''}{c.points})</option>)}</select><label>Wie deden mee?</label><div className="person-grid">{participants.map(p=><button type="button" className={selected.includes(p.id)?'selected':''} onClick={()=>toggle(p.id)} key={p.id}>{selected.includes(p.id)&&<Check/>}{p.display_name}</button>)}</div>{challenge?.challenge_type==='bonus'&&<small>Bonusopdracht: alle zeven deelnemers ontvangen na goedkeuring de punten.</small>}{challenge?.challenge_type==='claim'&&<><label>Behaalde prestatie ({challenge.metric_unit})</label><input required type="number" step="any" value={performance} onChange={e=>setPerformance(e.target.value)}/></>}<label>Toelichting</label><textarea value={note} onChange={e=>setNote(e.target.value)}/><label className="upload-zone"><Camera/><strong>{file?file.name:'Foto toevoegen'}</strong><span>JPG, PNG of WebP</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files[0])}/></label>{error&&<div className="error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Upload/>} Versturen naar jury</button></form></section></div>
}
function PageIntro({eyebrow,title,text}){return <section className="page-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{text}</p></section>}
function Empty({text}){return <div className="empty"><Sparkles/><p>{text}</p></div>}
